{
	"id": 706,
	"objectId": 27,
	"customUIRoleList": [{
		"roleId": 2
	}],
	"name": "新建界面",
	"type": 1,
	"isDefault": 1,
	"fieldPermissionsList": [{
		"fieldIdPath": "308"
	}, {
		"fieldIdPath": "309"
	}, {
		"fieldIdPath": "310"
	}, {
		"fieldIdPath": "311"
	}, {
		"fieldIdPath": "312"
	}, {
		"fieldIdPath": "29513",
		"permissionCode": 4
	}],
	"extendFieldPermissionsList": [],
	"fieldMap": {
		"308": {
			"id": 308,
			"customObjectId": 27,
			"label": "创建时间",
			"apiName": "createTime",
			"fieldType": 6,
			"isPrimary": 0,
			"permissionCode": 2,
			"isVisible": 1,
			"isEditable": 0,
			"isRequired": 0,
			"isStandard": 1,
			"isSystem": 1,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"imagePermission": 0,
			"attachmentPermission": 0,
			"isTagShow": 1
		},
		"309": {
			"id": 309,
			"customObjectId": 27,
			"label": "更新时间",
			"apiName": "updateTime",
			"fieldType": 6,
			"isPrimary": 0,
			"permissionCode": 2,
			"isVisible": 1,
			"isEditable": 0,
			"isRequired": 0,
			"isStandard": 1,
			"isSystem": 1,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"imagePermission": 0,
			"attachmentPermission": 0,
			"isTagShow": 1
		},
		"310": {
			"id": 310,
			"customObjectId": 27,
			"label": "创建人",
			"apiName": "createUser",
			"fieldType": 21,
			"isPrimary": 0,
			"permissionCode": 2,
			"isVisible": 1,
			"isEditable": 0,
			"isRequired": 0,
			"isStandard": 1,
			"isSystem": 1,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"foreignObjectId": 0,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"imagePermission": 0,
			"attachmentPermission": 0,
			"isTagShow": 1
		},
		"311": {
			"id": 311,
			"customObjectId": 27,
			"label": "修改人",
			"apiName": "updateUser",
			"fieldType": 21,
			"isPrimary": 0,
			"permissionCode": 2,
			"isVisible": 1,
			"isEditable": 0,
			"isRequired": 0,
			"isStandard": 1,
			"isSystem": 1,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"foreignObjectId": 0,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"imagePermission": 0,
			"attachmentPermission": 0,
			"isTagShow": 1
		},
		"312": {
			"id": 312,
			"customObjectId": 27,
			"label": "所有人",
			"apiName": "owner",
			"fieldType": 23,
			"isPrimary": 0,
			"permissionCode": 4,
			"isVisible": 1,
			"isEditable": 1,
			"isRequired": 0,
			"isStandard": 1,
			"isSystem": 1,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"foreignObjectId": 0,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"imagePermission": 0,
			"attachmentPermission": 0,
			"isTagShow": 1
		},
		"29513": {
			"id": 29513,
			"customObjectId": 27,
			"label": "货品",
			"apiName": "huopin",
			"fieldType": 19,
			"isPrimary": 0,
			"permissionCode": 4,
			"isVisible": 1,
			"isEditable": 1,
			"isRequired": 0,
			"isStandard": 0,
			"isSystem": 0,
			"isSearchable": 0,
			"isSearchForward": 0,
			"isMatchingPriority": 0,
			"optionShowType": 1,
			"isUnique": 0,
			"foreignObjectId": 1351,
			"isGenerateExisting": 0,
			"isOuterUniqueId": 0,
			"isSupportAttachment": 0,
			"isDeleted": 0,
			"scanType": 0,
			"referGroupId": 0,
			"orders": 0,
			"fieldClassify": 1,
			"isPrimaryGroupInnerField": 0,
			"validateRuleId": 0,
			"fieldNullSetType": 1,
			"fieldNullCalcType": 1,
			"isTagShow": 1
		}
	},
	"widgetJson": "{\"widgets\":[{\"instance\":{\"widgets\":[{\"instance\":{\"id\":\"instance-customButton-20\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-21\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮2\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-32\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮4\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-33\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮5\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-34\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮6\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-35\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮7\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-36\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮8\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-37\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮9\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-38\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮10\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-39\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮11\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-40\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮12\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}},{\"instance\":{\"id\":\"instance-customButton-41\",\"config\":{\"customButtonId\":null,\"customButtonName\":\"test1（已废弃）\",\"name\":\"按钮13\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"customButton\",\"data\":null}}],\"id\":\"instance-buttons-1\",\"config\":{\"name\":\"操作区1\",\"belongToObjectId\":27}},\"descriptor\":{\"type\":\"buttons\"}},{\"instance\":{\"widgets\":[{\"instance\":{\"id\":\"instance-abstract-70\",\"config\":{\"showFields\":[],\"name\":\"摘要1\",\"belongToObjectId\":27},\"widgets\":[{\"instance\":{\"id\":\"instance-abstractField-71\",\"config\":{\"name\":\"摘要字段1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"abstractField\",\"data\":{\"field\":{\"id\":308,\"customObjectId\":27,\"label\":\"创建时间\",\"apiName\":\"createTime\",\"fieldType\":6,\"isPrimary\":0,\"permissionCode\":2,\"isVisible\":1,\"isEditable\":0,\"isRequired\":0,\"isStandard\":1,\"isSystem\":1,\"isSearchable\":0,\"isSearchForward\":0,\"isMatchingPriority\":0,\"optionShowType\":1,\"isUnique\":0,\"isGenerateExisting\":0,\"isOuterUniqueId\":0,\"isSupportAttachment\":0,\"isDeleted\":0,\"scanType\":0,\"referGroupId\":0,\"orders\":0,\"fieldClassify\":1,\"isPrimaryGroupInnerField\":0,\"validateRuleId\":0,\"fieldNullSetType\":1,\"fieldNullCalcType\":1,\"imagePermission\":0,\"attachmentPermission\":0,\"isTagShow\":1},\"fullFieldPath\":308}}},{\"instance\":{\"id\":\"instance-abstractField-72\",\"config\":{\"name\":\"摘要字段2\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"abstractField\",\"data\":{\"field\":{\"id\":309,\"customObjectId\":27,\"label\":\"更新时间\",\"apiName\":\"updateTime\",\"fieldType\":6,\"isPrimary\":0,\"permissionCode\":2,\"isVisible\":1,\"isEditable\":0,\"isRequired\":0,\"isStandard\":1,\"isSystem\":1,\"isSearchable\":0,\"isSearchForward\":0,\"isMatchingPriority\":0,\"optionShowType\":1,\"isUnique\":0,\"isGenerateExisting\":0,\"isOuterUniqueId\":0,\"isSupportAttachment\":0,\"isDeleted\":0,\"scanType\":0,\"referGroupId\":0,\"orders\":0,\"fieldClassify\":1,\"isPrimaryGroupInnerField\":0,\"validateRuleId\":0,\"fieldNullSetType\":1,\"fieldNullCalcType\":1,\"imagePermission\":0,\"attachmentPermission\":0,\"isTagShow\":1},\"fullFieldPath\":309}}},{\"instance\":{\"id\":\"instance-abstractField-73\",\"config\":{\"name\":\"摘要字段3\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"abstractField\",\"data\":{\"field\":{\"id\":310,\"customObjectId\":27,\"label\":\"创建人\",\"apiName\":\"createUser\",\"fieldType\":21,\"isPrimary\":0,\"permissionCode\":2,\"isVisible\":1,\"isEditable\":0,\"isRequired\":0,\"isStandard\":1,\"isSystem\":1,\"isSearchable\":0,\"isSearchForward\":0,\"isMatchingPriority\":0,\"optionShowType\":1,\"isUnique\":0,\"foreignObjectId\":0,\"isGenerateExisting\":0,\"isOuterUniqueId\":0,\"isSupportAttachment\":0,\"isDeleted\":0,\"scanType\":0,\"referGroupId\":0,\"orders\":0,\"fieldClassify\":1,\"isPrimaryGroupInnerField\":0,\"validateRuleId\":0,\"fieldNullSetType\":1,\"fieldNullCalcType\":1,\"imagePermission\":0,\"attachmentPermission\":0,\"isTagShow\":1},\"fullFieldPath\":310}}},{\"instance\":{\"id\":\"instance-abstractField-74\",\"config\":{\"name\":\"摘要字段4\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"abstractField\",\"data\":{\"field\":{\"id\":311,\"customObjectId\":27,\"label\":\"修改人\",\"apiName\":\"updateUser\",\"fieldType\":21,\"isPrimary\":0,\"permissionCode\":2,\"isVisible\":1,\"isEditable\":0,\"isRequired\":0,\"isStandard\":1,\"isSystem\":1,\"isSearchable\":0,\"isSearchForward\":0,\"isMatchingPriority\":0,\"optionShowType\":1,\"isUnique\":0,\"foreignObjectId\":0,\"isGenerateExisting\":0,\"isOuterUniqueId\":0,\"isSupportAttachment\":0,\"isDeleted\":0,\"scanType\":0,\"referGroupId\":0,\"orders\":0,\"fieldClassify\":1,\"isPrimaryGroupInnerField\":0,\"validateRuleId\":0,\"fieldNullSetType\":1,\"fieldNullCalcType\":1,\"imagePermission\":0,\"attachmentPermission\":0,\"isTagShow\":1},\"fullFieldPath\":311}}},{\"instance\":{\"id\":\"instance-abstractField-75\",\"config\":{\"name\":\"摘要字段5\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"abstractField\",\"data\":{\"field\":{\"id\":312,\"customObjectId\":27,\"label\":\"所有人\",\"apiName\":\"owner\",\"fieldType\":23,\"isPrimary\":0,\"permissionCode\":4,\"isVisible\":1,\"isEditable\":1,\"isRequired\":0,\"isStandard\":1,\"isSystem\":1,\"isSearchable\":0,\"isSearchForward\":0,\"isMatchingPriority\":0,\"optionShowType\":1,\"isUnique\":0,\"foreignObjectId\":0,\"isGenerateExisting\":0,\"isOuterUniqueId\":0,\"isSupportAttachment\":0,\"isDeleted\":0,\"scanType\":0,\"referGroupId\":0,\"orders\":0,\"fieldClassify\":1,\"isPrimaryGroupInnerField\":0,\"validateRuleId\":0,\"fieldNullSetType\":1,\"fieldNullCalcType\":1,\"imagePermission\":0,\"attachmentPermission\":0,\"isTagShow\":1},\"fullFieldPath\":312}}}]},\"descriptor\":{\"type\":\"abstract\",\"data\":null}}],\"id\":\"instance-abstractContainer-2\",\"config\":{\"name\":\"摘要区1\",\"belongToObjectId\":27}},\"descriptor\":{\"type\":\"abstractContainer\"}},{\"instance\":{\"widgets\":[{\"instance\":{\"id\":\"instance-section-64\",\"config\":{\"cols\":[{\"width\":1}],\"nameHide\":false,\"name\":\"区域1\",\"belongToObjectId\":27},\"widgets\":[{\"instance\":{\"id\":\"instance-sectionItem-65\",\"config\":{\"name\":\"区域子组件1\",\"belongToObjectId\":27},\"widgets\":[{\"instance\":{\"id\":\"instance-fieldsMatrix-66\",\"config\":{\"nameHide\":false,\"cols\":\"1\",\"rows\":\"1\",\"alignType\":1,\"positionType\":\"2\",\"labelWidth\":null,\"name\":\"记录字段11\",\"belongToObjectId\":27},\"widgets\":[{\"instance\":{\"id\":\"instance-fieldsMatrixItem-67\",\"config\":{\"name\":\"记录字段子组件1\",\"belongToObjectId\":27},\"widgets\":[{\"instance\":{\"id\":\"instance-field-68\",\"config\":{\"permissionCode\":4,\"isLookUserModalSetting\":true,\"isSelectDisplayTypeSetting\":true,\"numberDisplayType\":\"\",\"rows\":1,\"cols\":1,\"name\":\"字段1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"field\",\"data\":{\"fullFieldPath\":29513,\"targetWidgetId\":\"instance-fieldsMatrix-66\"}}}]},\"descriptor\":{\"type\":\"fieldsMatrixItem\"}}]},\"descriptor\":{\"type\":\"fieldsMatrix\",\"data\":null}},{\"instance\":{\"id\":\"instance-stockSearch-84\",\"config\":{\"nameHide\":false,\"rows\":\"10\",\"name\":\"库存查询1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"stockSearch\",\"data\":null}},{\"instance\":{\"id\":\"instance-todoList-76\",\"config\":{\"nameHide\":false,\"rows\":1,\"pageSize\":5,\"name\":\"待办事项1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"todoList\",\"data\":null}},{\"instance\":{\"id\":\"instance-teamMember-77\",\"config\":{\"nameHide\":false,\"rows\":3,\"showFields\":[{\"fieldId\":\"name\",\"fieldName\":\"姓名\"},{\"fieldId\":\"jobs\",\"fieldName\":\"岗位\"},{\"fieldId\":\"role\",\"fieldName\":\"团队角色\"},{\"fieldId\":\"permission\",\"fieldName\":\"权限\"},{\"fieldId\":\"mobile\",\"fieldName\":\"手机\"}],\"name\":\"团队成员1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"teamMember\",\"data\":null}},{\"instance\":{\"id\":\"instance-approvalRecord-78\",\"config\":{\"nameHide\":false,\"isMustHasApprovalShow\":false,\"name\":\"审批记录1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"approvalRecord\",\"data\":null}},{\"instance\":{\"id\":\"instance-objectRelation-79\",\"config\":{\"nameHide\":false,\"rows\":5,\"pitchOnFieldIds\":[],\"name\":\"对象关系1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"objectRelation\",\"data\":null}},{\"instance\":{\"id\":\"instance-email-80\",\"config\":{\"nameHide\":false,\"rows\":1,\"defaultRecipients\":null,\"defaultEmailData\":{},\"name\":\"邮件1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"email\",\"data\":null}},{\"instance\":{\"id\":\"instance-relatedRecord-81\",\"config\":{\"nameHide\":false,\"rows\":1,\"isAddRelatedRecord\":false,\"isEditRelatedRecord\":false,\"name\":\"相关记录1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"relatedRecord\",\"data\":null}},{\"instance\":{\"id\":\"instance-trajectory-82\",\"config\":{\"nameHide\":false,\"rows\":5,\"origin\":null,\"startTime\":null,\"endTime\":null,\"destinationLocaltion\":null,\"unit\":1,\"name\":\"轨迹1\",\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"trajectory\",\"data\":null}},{\"instance\":{\"id\":\"instance-timeLine-83\",\"config\":{\"name\":\"时间轴1\",\"stageBackgroundColor\":\"#39bb9c\",\"position\":1,\"stages\":[],\"belongToObjectId\":27},\"widgets\":[]},\"descriptor\":{\"type\":\"timeLine\",\"data\":null}}]},\"descriptor\":{\"type\":\"sectionItem\"}}]},\"descriptor\":{\"type\":\"section\",\"data\":null}}],\"id\":\"instance-root-2\",\"config\":{\"name\":\"根1\",\"belongToObjectId\":27}},\"descriptor\":{\"type\":\"root\"}}]}",
	"objectRelationUIInfoList": [{
		"widgetId": "instance-objectRelation-79",
		"showFieldList": []
	}],
	"customUIRuleItemList": [],
	"relateRecordSetting": {
		"actionWidgetList": []
	},
	"emailSetting": {
		"emailWidgetList": [{
			"widgetId": "instance-email-80",
			"receiverList": []
		}]
	},
	"smsSetting": {
		"smsWidgetList": []
	},
	"fieldConditionSetting": {
		"fieldConditionList": []
	},
	"creatorComponentSetting": {
		"creatorComponentWidgetList": []
	},
	"fieldDataList": [],
	"fieldUIPermissionList": [{
		"fieldIdPath": "308"
	}, {
		"fieldIdPath": "309"
	}, {
		"fieldIdPath": "310"
	}, {
		"fieldIdPath": "311"
	}, {
		"fieldIdPath": "312"
	}, {
		"fieldIdPath": "29513",
		"permissionCode": 4
	}],
	"fieldUISettingList": [],
	"relatedObjFieldPathList": [],
	"extendFieldUIPermissionList": [],
	"remarkSetting": {
		"remarkWidgetList": []
	}
}