{
  "id": 4259,
  "customObjectId": 64,
  "label": "汇总字段",
  "apiName": "huizongziduan",
  "fieldType": 33,
  "decimalDigits": 1,
  "isPrimary": 0,
  "permissionCode": 2,
  "isVisible": 1,
  "isEditable": 0,
  "isRequired": 0,
  "isStandard": 0,
  "isSystem": 0,
  "isSearchable": 0,
  "isSearchForward": 0,
  "isMatchingPriority": 0,
  "optionShowType": 1,
  "isUnique": 0,
  "foreignObjectId": 64,
  "expressionForm": "{\"type\":5,\"foreignFieldId\":1115,\"foreignOrderFieldId\":null}",
  "judgeStrategy": 1,
  "conditionList": [{
    "fieldList": [{
      "id": 4260
    }],
    "operator": "is",
    "value": null
  }],
  "isGenerateExisting": 0,
  "isOuterUniqueId": 0,
  "isSupportAttachment": 0,
  "resultFieldType": 7,
  "isDeleted": 0,
  "scanType": 0,
  "referGroupId": 0,
  "orders": 0,
  "fieldClassify": 1,
  "isPrimaryGroupInnerField": 0,
  "validateRuleId": 0,
  "fieldNullSetType": 1,
  "summaryFieldNullShowType": 1,
  "fieldNullCalcType": 1,
  "isTagShow": 1,
  "isStatisticsRelation": 1,
  "metadataObjectRelationIds": "2"
}
